run_id: 
dataset:
    module: data.gf_loader
    class: GFLoader
    path: DATA/brca_full/cancer_cells_only.h5ad #path is relative to DATA_PATH in setup_path.py
    load_raw: False
    label_key: cohort
    batch_key: Cancer_type
    filter: 
      - column: timepoint
        values:
          - Pre
    layer_name: X  #if data exist in another layer (e.g. adta.layers['counts']). The data will be copied to adata.X
    train_test_split: data_splits/brca_full/brca_chemo/train_test_split_oversampled.json #path is relative to BASE_PATH in setup_path.py
    cv_splits: data_splits/brca_full/brca_chemo/cv_splits_oversampled.json #path is relative to BASE_PATH in setup_path.py

qc:
    # skip: True
    min_genes: 10
    min_cells: 10

preprocessing:
    # skip: True
    normalize: True
    target_sum: 10000
    apply_log1p: True

hvg:
    batch_key: batch
    n_top_genes: 2048
    flavor: seurat # expect logarithmized data
    
embedding:
    method: geneformer
    module: features.gf_extractor
    class: GeneformerExtractor
    viz: True
    eval: True
    params: 
        #1- Genefromer 1
        model: Geneformer-V1-10M 
        version: V1
        model_dir: /home/jupyter/MODELS/Geneformer/
        dict_dir: /home/jupyter/MODELS/Geneformer/geneformer/gene_dictionaries_30m #genefromer 1
        input_size: 2048
        batch_size: 16
        continue_training:
            learning_rate: 0.001
            do_train: True
            do_eval: False
            group_by_length: True
            length_column_name: length
            disable_tqdm: False
            lr_scheduler_type: linear
            warmup_steps: 10000
            weight_decay: 0.001
            per_device_train_batch_size: 16
            num_train_epochs: 6
            save_strategy: 'epoch' #'steps' 

classification:
    skip: False
    module: models.classify
    class: ClassifierPipeline
    params:
        model: randomforest
        n_estimators: 100
        max_depth: 5
        cv: True
        label_map:
              treatment_naive: 0
              neoadjuvant_chemo: 1
    viz: True
    eval: True
