run_id: 
dataset:
    module: data.gf_loader
    class: GFLoader
    path: mnt/DATA/brca_full/cancer_cells_only.h5ad #path is relative to DATA_PATH in setup_path.py
    load_raw: False
    label_key: Cancer_type
    batch_key: donor_id
    filter: 
      - column: Cancer_type
        values:
          - ER+
          - TNBC
      - column: timepoint
        values:
          - Pre
    layer_name: X  #if data exist in another layer (e.g. adta.layers['counts']). The data will be copied to adata.X
    train_test_split: data_splits/brca_full/brca_subtype/train_test_split.json #path is relative to BASE_PATH in setup_path.py
    cv_splits: data_splits/brca_full/brca_subtype/cv_splits.json #path is relative to BASE_PATH in setup_path.py
qc:
    min_genes: 10
    min_cells: 10

preprocessing:
    normalize: True
    target_sum: 10000
    apply_log1p: True

hvg:
    batch_key: batch
    n_top_genes: 4096
    flavor: seurat # expect logarithmized data
    
    
embedding:
    skip: True # dont excute this (embedding) step
    viz: False
    eval: False

classification:
    module: models.gf_finetune
    class: GFFineTuneModel
    params:
        model: Geneformer-V2-104M
        version: V2
        model_dir: /home/jupyter/mnt/MODELS/
        dict_dir: /home/jupyter/mnt/gf_dicts_v2 #genefromer 2
        model_input_size: 4096
        batch_size: 32
        epoch: 3
        freeze_layers: 0
        learning_rate: 5e-05
        weight_decay: 0
        warmup_ratio: 0
        train_funcs: 
            # - avg
            # - mil
            - vote
        cv: True
        label_map:
              ER+: 0
              TNBC: 1
    viz: True
    eval: True
